/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Laptop.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['LapTop_Cube002-Mesh']: THREE.Mesh
    ['LapTop_Cube002-Mesh_1']: THREE.Mesh
    ['LapTop_Cube002-Mesh_2']: THREE.Mesh
    ['LapTop_Cube002-Mesh_3']: THREE.Mesh
  }
  materials: {
    DarkGray: THREE.MeshStandardMaterial
    lighterGray: THREE.MeshStandardMaterial
    Gray2: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/Laptop.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['LapTop_Cube002-Mesh'].geometry} material={materials.DarkGray} />
      <mesh geometry={nodes['LapTop_Cube002-Mesh_1'].geometry} material={materials.lighterGray} />
      <mesh geometry={nodes['LapTop_Cube002-Mesh_2'].geometry} material={materials.Gray2} />
      <mesh geometry={nodes['LapTop_Cube002-Mesh_3'].geometry} material={materials.Screen} />
    </group>
  )
}

useGLTF.preload('/Laptop.glb')
